from tkinter import *

main = Tk()

def Decision(decision):
    if decision == "Rent":
        w = Label(main, Rent(decision))
        w.pack()
    elif decision == "Sell":
        w = Label(main, Sell(decision))
        w.pack()
    elif decision == "Combined":
        w = Label(main, Combined(decision))
        w.pack()


def Rent(decision):
    Label(page2, text = "Price of the area in euro").grid(row = 0)
    purchasing_area = Entry(page2)
    purchasing_area.grid(row = 0, column = 1)
    Label(page2, text = "Price of the construction in euro:").grid(row = 1)
    construction_price = Entry(page2)
    construction_price.grid(row = 1, column = 1)
    Label(page2, text = "Enter the area in m*m:")
    area = Entry(page2)
    area.grid(row = 2, column = 1)
    Label(page2, text = "Enter the number of floors:").grid(row = 2)
    floors = Entry(page2)
    floors.grid(row = 2, column = 1)
    construction_area = area*floors
    Label(page2, text = "Enter the rent price for 1 m*m per month:").grid(row = 3)
    rent = Entry(page2)
    rent.grid(row = 3, column = 1)
    Label(page2, text = "Profit months:").grid(row = 4)
    months = Entry(page2)
    months.grid(row = 4, column = 1)
    Label(page2, text = "Price of the construction maintenance for month in euro:").grid(row = 5)
    construction_maintenance = Entry(page2)
    construction_maintenance.grid(row = 5, column = 1)
    residue_after_payments = user.income-construction_price-purchasing_area
    income_for_month = (construction_area*rent)-construction_maintenance
    x = int((user.income-residue_after_payments)/income_for_month)
    j = months*(area*rent-construction_maintenance)
    p = j-x*(area*rent-construction_maintenance)
    if residue_after_payments >= 0:
        w = Label(main, text = "There are")
        w.pack()
        w = Label(main, text = residue_after_payments)
        w.pack()
        w = Label(main, text = "euros left!")
        w.pack()
        w = Label(main, text = "You will return your investments in")
        w.pack()
        w = Label(main, text = x)
        w.pack()
        w = Label(main, text = "months")
        w.pack()
        w = Label(main, text = "Your income for")
        w.pack()
        w = Label(main, text = months)
        w.pack()
        w = Label(main, text = "months is")
        w.pack()
        w = Label(main, text = p)
        w.pack()
	
    else:
        q = Label(main, text = "You must pay")
        q.pack()
        q = Label(main, text = 0-residue_after_payments)
        q.pack()
        q = Label(main,text = "euros")
        q.pack()
        e = Label(main, text = "You can make the payment after:")
        e.pack()
        e = Label(main, int(x))
        e.pack()
        r = Label(main,text = 'Income for month is')
        r.pack()
        r = Label(main,text = income_for_month)
        r.pack()
        t = Label(main, text = "The summarized area is")
        t.pack()
        t = Label(main, text = construction_area)
        t.pack()

def Sell(decision):
    Label(page2, text = "Price of the area in euro:").grid(row = 6)
    purchasing_area1 = Entry(page2)
    purchasing_area1.grid(row = 6, column = 1)
    Label(page2, text = "Price of the construction in euro:").grid(row = 7)
    construction_price1 = Entry(page2)
    construction_price1.grid(row = 7, column = 1)
    income_after_payments1 = user.income-construction_price1-purchasing_area1 
    Label(page2, text = "Price of the selling area:").grid(row = 8)
    selling_area = Entry(page2)
    selling_area.grid(row = 8, column = 1)
    gains = selling_area-purchasing_area1-construction_price1
    y = Label(main, text = "Your gains are")
    y.pack()
    y = Label(main, text = gains)
    y.pack()
    
def Combined(decision):
    Label(page2, text = "The percentage of the sellings(The part of your possessions you want to sell.):").grid(row = 9)
    percentage_of_sellings = Entry(page2)
    percentage_of_sellings.grid(row = 9, column = 1)
    Label(page2, text = "The percentage of the rents(The part of things(for example: apartments)you want to rent.):").grid(row = 10)
    percentage_of_rents = Entry(page2)
    percentage_of_rents.grid(row = 10, column = 1)
    Label(page2, text = "Price of the construction in euro:").grid(row = 11)
    construction_price1 = Entry(page2)
    construction_price1.grid(row = 11, column = 1)
    Label(page2, text = "Price of the area in euro:").grid(row = 12)
    purchasing_area1 = Entry(page2)
    purchasing_area1.grid(row = 12, column = 1)
    Label(page2, text = "Price of the selling area:").grid(row = 13)
    selling_area = Entry(page2)
    selling_area.grid(row = 13, column = 1)
    residue_after_payments = user.income-construction_price1-purchasing_area1
    gains = selling_area-purchasing_area1-construction_price1
    Label(page2, text = "Enter the rent price for 1 m*m per month:").grid(row = 14)
    rent = Entry(page2)
    rent.grid(row = 14, column = 1)
    Label(page2, text = "Price of the construction maintenance for month in euro:").grid(row = 15)
    construction_maintenance = Entry(page2)
    construction_maintenance.grid(row = 15, column = 1)
    Label(page2, text = "Enter the area in m*m:").grid(row = 16)
    area = Entry(page2)
    area.grid(row = 16, column = 1)
    Label(page2, text = "Enter the number of floors:").grid(row = 17)
    floors = Entry(page2)
    floors.grid(row = 17, column = 1)
    construction_area = area*floors
    Label(page2, text = "Profit months:").grid(row = 18)
    months = Entry(page2)
    months.grid(row = 18, column = 1)
    income_for_month = (construction_area*rent)-construction_maintenance
    j = months*(area*rent-construction_maintenance)
    earnings = (percentage_of_rents/100)*j + (percentage_of_sellings/100)*gains
    y = int(((construction_price1 + purchasing_area1) - gains-construction_price1-purchasing_area1)/income_for_month)
    earnings_after_payments = int(earnings - y)
    
    
    if earnings > 0:
        u = Label(main,text = "You will receive")
        u.pack()
        u = Label(main, text = earnings)
        u.pack()
        o = Label(main, text = "Do it if you want!")
        o.pack()
        o = Label(main, text = "After")
        o.pack()
        o = Label(main, text = y)
        o.pack()
        o = Label(main, text = "months you will return your payments")
        o.pack()
        o = Label(main, text = "Your resedue after payments is")
        o.pack()
        o = Label(main, text = earnings_after_payments)
        o.pack()
        
    elif earnings == 0:
        p = Label(main, text = earnings)
        p.pack()
        p = Label(main, text = "You will not receive anything!")
        p.pack()
        a = Label(main, text = "There is no point of doing this!")
        a.pack()
	
    else:
        s = Label(main, text = "You must pay")
        s.pack()
        s = Label(main, text = 0 - earnings)
        s.pack()
        s = Label(main, text = "euro!")
        s.pack()
        d = Label(main, text = "Do NOT do invest in this or take credit!")
        d.pack()
